name: gunnison_playground
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  gunnison: any
  gunnison_assets: any
  gunnison_web: any
dev_dependencies:
  gunnison_builder: any
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
dependency_overrides:
  gunnison:
    path: ../gunnison
  gunnison_assets:
    path: ../gunnison_assets
  gunnison_builder:
    path: ../gunnison_builder
  gunnison_web:
    path: ../gunnison_web
