name: aspen_playground
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  aspen: any
  aspen_assets: any
  aspen_web: any
dev_dependencies:
  aspen_builder: any
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
dependency_overrides:
  aspen:
    path: ../aspen
  aspen_assets:
    path: ../aspen_assets
  aspen_builder:
    path: ../aspen_builder
  aspen_web:
    path: ../aspen_web
