name: aspen
version: 0.2.3
description: A modern, easy-to-use asset packer
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/aspen
dependencies:
  ansicolor: ^1.0.0
  args: ^1.4.4
  csslib: ^0.14.5
  path: ^1.6.2
  yaml: ^2.1.15
executables:
  aspen:
environment:
  sdk: ">=2.0.0 <3.0.0"
