name: aspen
version: 0.1.1
description: A modern, easy-to-use asset packer
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/aspen
dependencies:
  ansicolor: ^0.0.9
  args: ^1.0.0
  path: ^1.5.0
  yaml: ^2.0.0
executables:
  aspen:
environment:
  sdk: ">=1.8.0 <2.0.0"
