name: gunnison_builder
version: 0.4.0
description: A modern, easy-to-use asset packer (builder package)
homepage: https://github.com/refi64/gunnison

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^5.8.0
  gunnison:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison
  build: ^2.3.1
  csslib: ^0.17.2
  source_gen: ^1.2.7
  base85: ^1.0.3

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  gunnison:
    path: ../gunnison
