name: aspen_builder
version: 0.3.0
description: A modern, easy-to-use asset packer (builder package)
homepage: https://github.com/refi64/aspen

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: '>=0.37.0 <0.40.0'
  aspen: ^0.3.0
  build: ^1.2.0
  csslib: ^0.16.1
  source_gen: ^0.9.4+3
  z85: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0

# dependency_overrides:
#   aspen:
#     path: ../aspen
