name: aspen_assets
version: 0.1.0
description: Access assets packed via Aspen in your Dart scripts
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/aspen
dependencies:
  js: ^0.6.1
environment:
  sdk: ">=1.8.0 <2.0.0"
