name: aspen_web
version: 0.3.0
description: A modern, easy-to-use asset packer (web package)
homepage: https://github.com/refi64/aspen

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  aspen: ^0.3.0+1
  aspen_assets: ^0.3.0
  js: ^0.6.7

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  aspen:
    path: ../aspen
  aspen_assets:
    path: ../aspen_assets
