name: aspen_demo
dependencies:
  aspen_assets: any
  browser: any
  dart_to_js_script_rewriter: any
dev_dependencies:
  aspen: any
dependency_overrides:
  aspen_assets:
    path: ../assets
  aspen:
    path: ..
transformers:
  - dart_to_js_script_rewriter
