targets:
  aspen_playground:
    sources:
      include:
        - 'benchmark/**'
        - 'bin/**'
        - 'example/**'
        - 'lib/**'
        - 'node_modules/**'
        - 'test/**'
        - 'tool/**'
        - 'web/**'
        - 'pubspec.yaml'
        - 'pubspec.lock'
