name: aspen
version: 0.3.0
description: A modern, easy-to-use asset packer
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/refi64/aspen

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
